#!/bin/bash
#=================================================
# File name: init-settings.sh
# Description: This script will be executed during the first boot
#=================================================
# Configure LAN
# More options: https://openwrt.org/docs/guide-user/base-system/basic-networking
lan_ip_address="192.168.123.1"
if [ -n "$lan_ip_address" ]; then
  uci set network.lan.ipaddr="$lan_ip_address"
  uci commit network
fi

# Configure PPPoE
# More options: https://openwrt.org/docs/guide-user/network/wan/wan_interface_protocols#protocol_pppoe_ppp_over_ethernet
pppoe_username="01234567890"
pppoe_password="123456"
if [ -n "$pppoe_username" -a "$pppoe_password" ]; then
  uci set network.wan.proto=pppoe
  uci set network.wan.username="$pppoe_username"
  uci set network.wan.password="$pppoe_password"
  uci commit network
fi

# Set default shell
which zsh && sed -i -- 's:/bin/bash:'`which zsh`':g' /etc/passwd
exit 0
